pypi-filelock: Autospec creation for update from version 3.15.1 to version 3.15.3
Bernát Gábor (1):
      Add test for virtualenv stability (#344)

Vitaliy Yelnik (2):
      Use a metaclass to implement the singleton pattern (#340)
      Fix `TypeError: _CountedFileLock.__init__() got an unexpected keyword argument 'timeout'` (#345)

dependabot[bot] (1):
      Bump pypa/gh-action-pypi-publish from 1.8.14 to 1.9.0 (#341)

pre-commit-ci[bot] (1):
      [pre-commit.ci] pre-commit autoupdate (#342)